### ISSUE TITLE
[1.13.7] stopped showing xkcd comics in the built-in viewer (Debian package)

### ISSUE THREAD

**Issue by paulgevers** [lwindolf/liferea#1054]
Hi,

Yesterday, I updated the Debian liferea package to 1.13.7. Today I noticed that my feed for xkcd (https://xkcd.com/atom.xml) doesn't show the comics anymore in the built-in viewer. I'm not sure if I'm doing something wrong in the packaging. If I downgrade to the previous version of the Debian package, the comics show again.

Is this expected?

Paul

Debian bug: https://bugs.debian.org/1001382

**Comment by paulgevers** [comment]
More info: with 1.13.6 it doesn't matter weather "Reader mode" is toggled or not. With 1.13.7 the comic only shows when "Reader mode" is *off*.

**Comment by mhoran** [comment]
I can reproduce. Interestingly, even going to xkcd.com and turning on reader view in Firefox has the same behavior (the comic disappears.) So whatever is happening in the page is blocked by Readability.

The image is completely removed by Readability so this isn't just a Liferea bug; once fixed in Readability this should be resolved.

**Comment by lwindolf** [comment]
That's bad. Many people including myself like xkcd :-(

**Comment by paulgevers** [comment]
Confirmed from my side too. I applied the changes from #1056 in the Debian package (had to change a bit due to the rename of htmlviewer.c but it looks OK).
