### ISSUE TITLE
persistent cookie storage for the webkit widget

### ISSUE THREAD

**Issue by fbellet** [lwindolf/liferea#108]
Having a persistent cookie storage in the webkit widget would allow to remember authentication information in the case of public feeds, that contains links to content requiring authentication. webkit2gtk provides such a capability (with WebKitCookieManager).

**Comment by lwindolf** [comment]
I see your use case now, the problem I have with simply implementing it is: it would decrease user privacy. Because right now there is no cookie persistence and almost no cookie based user tracking.

When implementing it it would need to be turned off per-default and one actually would quickly need a per-domain cookie management as we have in major browser. That's a type of complexity I cannot maintain due to lack of time.

**Comment by lwindolf** [comment]
For now I believe there are more users that care about security/anonymity, so I decided to go with the secure (session cookie only) default.
