### ISSUE TITLE
Wait for the network to become fully available before trying a planned mass refresh

### ISSUE THREAD

**Issue by nekohayo** [lwindolf/liferea#1121]
On my desktop computer, Liferea 1.13.7 (and previous versions) is set to:
* Update all feed subscriptions on startup, and...
* Default refresh interval: 3 hours

The problem is, I leave Liferea running on it, my computer goes to sleep automatically, and when I come back in the morning I am faced with this big wall of ⛔, which tells me it has tried to refresh everything "while the computer was waking up" (which takes a couple of seconds) before Network-Manager was fully ready:

![Screenshot from 2022-06-01 10-21-08](https://user-images.githubusercontent.com/479401/171427165-5fe1a04e-3121-4941-94b8-4a4751e40612.png)

The result is not only that it looks broken/ugly, but presumably Liferea also misses/abandons the window of opportunity to refresh those feeds, so the user is stuck with outdated feeds for a while because Liferea was "too precipitated".

I am using a wired gigabit connection on this computer so in theory the network device is ready faster than I can notice / unlock the screen, but apparently that's not "fast enough" for Liferea. I suspect the problem would be even more pronounced with a computer that depends on a wireless network adapter, which could easily take 10-30 seconds to wake up, find and connect to the network.

Liferea could withhold updating its feeds for maybe 30 seconds when waking up from sleep (not sure how it would detect that), or, probably better / cleaner, use Network-Manager's APIs to be sure the network is fully available _with unfettered access to the Internet_ (i.e. not behind a captive portal, or with the LAN up but WAN out-of-service, or that sort of thing).

According to the documentation found in https://people.freedesktop.org/~lkundrak/nm-docs/ (I'm not sure if that's the "new" official place), there is a "[nm-online](https://people.freedesktop.org/~lkundrak/nm-docs/nm-online.html)" commandline utility to check the state, and the [D-Bus API types](https://people.freedesktop.org/~lkundrak/nm-docs/nm-dbus-types.html) distinguish between various connectivity states. Possibly (I'm just guessing because there's so many things in there) you want to be watching `NMConnectivityState` for the presence of `NM_CONNECTIVITY_FULL`, as all other lower states would be problematic for Liferea (but it could use those states to indicate in the UI why it is waiting for NM to have full connectivity to the Internet before it updates).

**Comment by lwindolf** [comment]
While changing the behaviour to check for `NM_CONNECTIVITY_FULL` would solve your use case it would break all intranet use cases.

I do not see an easy solution right now.

**Comment by nekohayo** [comment]
Are there really people out there using a Linux feed reader to check an intranet's syndication feeds without access to the Internet at all? Honest question, as I have very rarely encountered Linux desktop users in big Intranet-enabled organizations, and rarely (if ever) seen an intranet offering syndication feeds. I'm wondering if that is your case, or purely a theoretical scenario. After all, remember that this would imply not just the above, but also require an organization that is so strict that it is basically "on-site work only, no remote, firewalled like hell, no access to Internet at all"... basically people working in a bunker cut off from the Internet... and that bunker somehow has an intranet _with syndication feeds!_ Sounds like an extremely unlikely combination.

If you've actually really seen this in the wild, then yeah I guess this could be hidden behind a gsettings/dconf key, but I think 99.9999% of people won't ever encounter such a scenario, unless they're working for DARPA.

**Comment by lwindolf** [comment]
Actually I'm part of the use case myself. When at work I consume intranet resources (security advisories, wiki updates, some ticket trackers, blogs of feature teams I'm interested) as much as possible via feed. Keeps me so much better informed. And internet is quite often not available directly.

**Comment by lwindolf** [comment]
Thought some more about it. One solution could be tying auto-updates to the `NM_CONNECTIVITY_FULL` state. So worst case for intranet users would be that they need to click "Update All" manually.

**Comment by lwindolf** [comment]
Solved by implementing hidden gconf property to enable intranet support. This was the lowest complexity solution. Please retest!

**Comment by jippiegithub** [comment]
In my local git log I see 'Fixes #1121: wait for network to become fully available.', a commit from December 17th and I built from these sources (it actually says version 1.14.0).
The number of failed feed retrievals dropped significantly since then. However today I noticed 'Liferea Blog' feed to fail. But OK, let's call that one an incident as I didn't notice this specific one before.

What I did notice is when using a command line as feed source, the feed is still synchronized while the network is being brought up. These feeds fail after opening the lid of my laptop. The easy solution is to add a `sleep 3;` at the start of the command line and all is fixed. For me that is an acceptable solution because I am aware of the issue and I know how to work around it. After reading the above I am not sure if there is a more structural solution, but at least making the developers aware.

I ran some tests past few days, capturing the output of the `ifconfig -a` command before the `sleep 3` and so far it is always the IPv6 global links that have not been brought up. I haven't captured any IPv4 problems, but that may be more luck than wisdom.

I hope the above feedback is useful.
