### ISSUE TITLE
Formation vanishes after a few seconds

### ISSUE THREAD

**Issue by Nudin** [lwindolf/liferea#1124]
I'm not sure if this is a known bug, I couldn't find an issue that I could clearly identify as the same effect.

The formation of news items sometimes vanishes, often in multiple phases. This video demonstrates the bug better than I can explain it:

https://user-images.githubusercontent.com/509205/176975288-52fedaa5-c909-482e-977a-ab72674701f0.mp4

**Comment by lwindolf** [comment]
I've changed the Webkit HTML rendering pane user stylesheet handling for just released 1.14-RC1. Could you please retest?

I believe this solves the suddenly vanishing style.

The content reload itself is to be expected when HTML5 extraction is enabled in the subscription properties. Once the HTML5 extraction suceeds, the content is reloaded.

So what we saw in your video worked probably like this:
1. you click and see the initial rendering (style ok, standard content)
2. some background update updates the rendering pane (style vanishes, standard content stays)
3. background HTML5 extraction runs (vanishes style stays, new content inserted)

So with 1.14-RC1 you should not see a transition between 1. and 2. anymore and the transition to 3. should be fine as the styles are still there.

Aside from this due to heise.de Javascript usage you get ugly `${intro}` stuff, but this is not a bug.

**Comment by lwindolf** [comment]
Additionally #1176 changed the stylesheet logic to work on URL protocol. This way no matter what background reloading the stylesheet is always correct. Transient states should now be gone.

**Comment by Nudin** [comment]
Updated a few days ago and haven't seen the problem since. Thanks!
