### ISSUE TITLE
Difficulty importing Webtoons links

### ISSUE THREAD

**Issue by CubeTheThird** [lwindolf/liferea#1125]
I have been having trouble importing feeds from https://www.webtoons.com.

Currently, if I navigate to a comic and press the RSS feed button, it asks to download an .rss file. Opening this file in Liferea works as expected. However, when actually trying to copy the feed URL as a new subscription, it fails at 

> 3. Feed Discovery

With the message:
> The source does not point directly to a feed or a webpage with a link to a feed!

I am unsure if there is a setting I should be enabling, of if there's something else I'm missing. If there is more info needed I am happy to provide.

**Comment by lwindolf** [comment]
You are doing nothing wrong here. The problem is with webtoons.com treating a non-browser with a GDPR confirmation.

When Liferea tries to auto-discover it gets redirected to https://www.webtoons.com/de/gdpr/ageGate and gives up.

There is no solution for this from the new reader side I fear. We had the issue with several other websites too, which after a while fixed their GDPR consent redirects.

**Comment by CubeTheThird** [comment]
Makes sense. What I ultimately did as a stop-gap is pipe it through a curl command, which does the trick. Thanks for looking into it.

**Comment by PetitMote** [comment]
Hi there,
Could you please share your curl command @CubeTheThird ?

**Comment by CubeTheThird** [comment]
> Hi there, Could you please share your curl command @CubeTheThird ?

It's literally just `curl "https://path/to/feed`, nothing special. I have the reader use a command source, which points to a bash script:

```
#!/bin/bash
curl "$1"
```

I then call it, passing it in the feed URL
