### ISSUE TITLE
When updating feeds liferea  interface freezes

### ISSUE THREAD

**Issue by ndias** [lwindolf/liferea#113]
Version 1.10.12

**Comment by mozbugbox** [comment]
From the code in `update.c`, it seems that all the update jobs are started _almost_ at the same time in the `update_dequeue_job()` call. It could cause inserting too much feed items at the same time without give the main loop a break, if soup queue message return data of different requests all at the same time.

The `update_dequeue_job()` returns `TRUE`. The intent is to have next update job called in next mainloop idle time. However, since the network activities are async, idle handler make not much different in this case. The results of network requests can still be returned at the same time.

On the other hand, `update_process_finished_job()` also called `update_dequeue_job()` in the front of the function. That call will make next update job started after the network activity of current update job is finished. This is good. Since `update_process_finished_job()` will always be called after a update job got its network data, I think this is enough to drain the queued update jobs in here, instead of let `update_dequeue_job()` recursively start downloading next update feed "almost immediately".

That is, the simplest solution is to let the `update_dequeue_job()` return `FALSE` instead of `TRUE` and let `update_process_finished_job()` to start the next update job.

If simultaneous feed downloading is desired, the `update_dequeue_job()` will keep returning `TRUE`. However, the call to the `update_process_finished_job()` inside `net.c->network_process_callback()` should be delayed in a idle handler, instead of called immediately. This will give main loop a break. And the `update_dequeue_job()` call inside `update_process_finished_job()` is redundant if I am not missing anything.

**Comment by nekohayo** [comment]
Just wanted to say this: cool analysis, @mozbugbox — it's great that you've taken the time to investigate this! (could it be that you're working on a patch for this? :)

**Comment by mozbugbox** [comment]
The freeze is not obvious on my machine. Maybe I don't have too much feed subscriptions. Or I am used to slow UI reaction. The UI feels jerky when update all but not really freeze for too long.

And on further looking, it seems that the heavey lifting part of `update_process_finished_job()` are already put into an idle handler in `update_process_result_idle_cb()`. 

The heavy lifting part, my guess is `subscription.c->subscription_process_update_result()`. I put a `debug_enter()/debug_exit()` in that function and I see most of the calls are around 500 ~ 2000ms. Well, that got to feel jerky.

**Comment by mozbugbox** [comment]
Upon further profiling :), it seems that most of the time are spent on, again, database upate, i.e. writing to the disk is slow.

I've come up a hack to batch sqlite operations into transaction. The data still have to be written to the disk at the end, but the time spent cut to ~half. The hack is at: mozbugbox@94bba79d2391cf66bab64e13132d315c5d67a59f

The code is not very clean. The place where the db operation happening and where transaction begin/end, are at the different places, even different files.

On the other hands, there could still be some **actual bugs** in the update code. When 2 consecutive  `Update All` actions are performed, there are always some db update operations in the 2nd run for some feeds. I think this should not happen.

**Comment by lwindolf** [comment]
@mozbugbox Thanks for investing so much time for analysis. This helps a lot. I agree that the "return TRUE" in update_dequeue_job() is causing cascading updates. I changed it to "return FALSE" in 1.10 and master branch. While I still experience freezing this already improves the situation.

In general there was a significant behaviour change around GNOME 3.14 that caused Liferea update fine-tuning to stop to work :-(

I fear I need to invest some time to catch up with this development to avoid user sufferings...

As for sqlite transactions I experimented with the in the past, but gave up due to deadlocks that happened from time to time.

**Comment by mozbugbox** [comment]
I think I found the actual bug that cause each update always write to the db for items marked as read.

At each update, downloaded items are always gone throught the `itemset.c -> itemset_merge_items() -> itemset_merge_item() -> itemset_generic_merge_check()`. The code in `itemset_generic_merge_check()` cause constant update on readed items. At line 120 of itemset.c, 
```c
	/* found corresponding item, check if they are REALLY equal (eg, read status may have changed) */
	if(oldItem->readStatus != newItem->readStatus) 
		equal = FALSE;
	if(oldItem->flagStatus != newItem->flagStatus)
		equal = FALSE;
```
This piece of code will always mark newly downloaded items as not equal, i.e. changed, if the olditem are marked as read. This will lead to most of newly downloaded items be flushed to db later on, even if they are already saved. It means worse disk load if all the item in a feed are catched up.

**Comment by rich-coe** [comment]
I've disabled these two if checks in my own branch of liferea.   These two lines were responsible for marking already read items back to unread.   I'm not sure how often they cause already stored items to be updated though.  I suppose it depends on the number of feeds that had this issue.

The following code marks the reason for re-inserting the item as unread.  You can do something similar to see why the feed items are marked.

                equal = TRUE;
                reason = 0;
 
                if (((item_get_title (oldItem) != NULL) && (item_get_title (newItem) != NULL)) &&  
                    (0 != strcmp (item_get_title (oldItem), item_get_title (newItem)))) {
                        equal = FALSE;
                        reason = 1;
                    }
 
                if (((item_get_description (oldItem) != NULL) && (item_get_description (newItem) != NULL)) && 
                    (0 != strcmp (item_get_description(oldItem), item_get_description (newItem)))) {
                        equal = FALSE;
                        reason |= 2;
                    }
 
                /* best case: they both have ids (position important: id check is useless without knowing if the items are different!) */
                if (item_get_id (oldItem)) {                    
    @@ -117,15 +123,20 @@ itemset_generic_merge_check (GList *items, itemPtr newItem, gint maxChecks, gboo
                                found = TRUE;
 
                                /* found corresponding item, check if they are REALLY equal (eg, read status may have changed) */
                               if(0 && oldItem->readStatus != newItem->readStatus) {
                                        equal = FALSE;
                                        reason |= 4;
                               }
                                if(0 && oldItem->flagStatus != newItem->flagStatus) {
                                        equal = FALSE;
                                        reason |= 8;
                                }
                                break;
                        } else {
                                /* different ids, but the content might be still equal (e.g. empty)
                                   so we need to explicitly unset the equal flag !!!  */
                                equal = FALSE;
                                reason |= 16;
                        }
                }
                        
    @@ -177,7 +188,7 @@ itemset_generic_merge_check (GList *items, itemPtr newItem, gint maxChecks, gboo
                                }
                                
                                db_item_update (oldItem);
                               debug1 (DEBUG_CACHE, "-> item already existing and was updated, reason %x", reason);
                        } else {
                                debug0 (DEBUG_CACHE, "-> item updates not merged because of parser errors");
                        }

**Comment by lwindolf** [comment]
Argh... How I hate the itemset merging. That's the worst and unmaintainable code in Liferea. The bug @mozbugbox pointed out was introduced by a change to make 2-way item state changes work for online new reader accounts. Since then the performance degradation must have been in place. So much for my blaming of GNOME 3.16...

@rich-coe using reason flags to make the code more transparent is a good idea. I'll probably add this and think a bit on a "simple" solution.

**Comment by mozbugbox** [comment]
Mabye a new flag in itemPtr to indicate where the newItem are from. Then the check for readStatus and flagStatus can be skippped for simple feed update.

**Comment by mozbugbox** [comment]
And should the checking for title/description be done **after** the item_get_id() check? And only needed if equal is TRUE after the item_get_id() test.

**Comment by lwindolf** [comment]
@rich-coe I added some more mitigation by preventing state updates causing normal (non-remote) feeds with a2cc35e

**Comment by lwindolf** [comment]
@mozbugbox Next I'll investigate how to change the remote source implementation to set alternative and exclusive flags to use in merging as suggested by you.

**Comment by lwindolf** [comment]
Closing this older ticket in favour of #792 which contains more recent relevant details.

Also creating an optimizing ticket to check out suggestion "And should the checking for title/description be done after the item_get_id() check? And only needed if equal is TRUE after the item_get_id() test." from @mozbugbox  -> #1108

Another optimizing ticket to check out suggestion "Mabye a new flag in itemPtr to indicate where the newItem are from. Then the check for readStatus and flagStatus can be skippped for simple feed update." from @mozbugbox -> #1109
