### ISSUE TITLE
Title header for folders (in the preview pane) gets wrapped onto multiple misaligned lines

### ISSUE THREAD

**Issue by nekohayo** [lwindolf/liferea#121]
As this screenshot (taken on 1.10.11) shows:

![capture d ecran de 2014-12-11 23 53 41](https://cloud.githubusercontent.com/assets/479401/5407346/104fc57c-8192-11e4-89aa-a52eebae19b0.png)

This happens only when clicking a folder, not individual feeds.

**Comment by lwindolf** [comment]
I believe this is a translation issue. FR translation introduced a whitespace that in conjunction with the CSS definitions caused a wrap. Please retest!

**Comment by nekohayo** [comment]
Haven't tested the git version, but I can confirm it's a translation issue as it does not occur when running "LANG=en_CA.UTF8 liferea"

**Comment by lwindolf** [comment]
Thanks for the retest!

**Comment by filorin** [comment]
In fact, this problem is because a "normal" space symbol was used. In french, we should use the "non breaking space", a special character to prevent word splitting. I'm trying to work on it in order to solve other problems like this caused by the French Translation. I already updated French Translation but it seems it does not change the problem (after compiling it on my own machine). If I find a solution, i'll will also propose it for the French-Canadian Translation.
