### ISSUE TITLE
Remove offline mode

### ISSUE THREAD

**Issue by Davidy22** [lwindolf/liferea#1245]
My vpn program makes the wifi indicator show not connected even when I am connected to wifi, which usually doesn't affect anything but specifically liferea detects this and goes into an offline mode where it will refuse to update, even though the inactive wifi is just a cosmetic bug from something else. It'd be nice if liferea didn't do this check and just attempted and failed to fetch if wifi genuinely was absent so that I can use liferea while on vpn

**Comment by nekohayo** [comment]
Hi, you didn't specify your Liferea version...

Liferea asks NetworkManager for various types of network online/semi-online states.

Unless there could be some additional check done through the NetworkManager API for VPNs, I believe the problem is the other way around: you should get your VPN thing fixed so that it doesn't break the whole system (as demonstrated by your broken system network connection indicator) rather than expect other Liferea users to have a degraded experience because of this. Besides, if it breaks your wifi indicator and Liferea, your VPN will also break other applications (such as mail clients like Evolution, etc.), so in my view it makes no sense for you to have to ask each app to ignore a broken network.

**Comment by lwindolf** [comment]
I agree with @nekohayo here. We abstract this into NetworkManager to have no extra handling in-app.
