### ISSUE TITLE
Date parsing fails on otherwise RFC822 dates with extra milliseconds

### ISSUE THREAD

**Issue by kvibber** [lwindolf/liferea#1299]
Liferea is unable to parse the timestamps in a feed generated by [bluestream](https://github.com/kawarimidoll/bluestream/), an RSS feed generator for Bluesky accounts. So Liferea stores the publication time as whatever time it retrieved the feed.

I ran the feed for my account through the [W3C feed validator](https://validator.w3.org/feed/), which turned up this issue:

> pubDate must be an RFC-822 date-time: 2023-08-29T19:59:32.672Z

It looks like Liferea's date parsing is failing on the milliseconds.

I'm reporting the issue to bluestream, since they should be generating the right date format, but it would be helpful for Liferea to handle this minor misformatting according to the robustness principle.

**Comment by lwindolf** [comment]
I feel your pain of not having proper dates in those feeds, but the RSS/Atom specs using RFC822 and ISO8601 are strongly specified, so that consuming applications can rely on this input.

From my perspective the relevant feeds are not valid and a feed reader should refuse to read those. Also looking at the complexity of date parsing code it's dangerous (stability-wise) to further complicate it.
