### ISSUE TITLE
A way to import tagged/flagged posts to a fresh install

### ISSUE THREAD

**Issue by bungadrum** [lwindolf/liferea#1368]
Do the feeds you have flagged with the tiny red dots get transferred when you reinstall Liferea to a new system and import them? I have a lot of bookmarks that I tagged that way and I want to know will they also transfer and be there when I import them?

**Comment by lwindolf** [comment]
There is a database in `~/.local/share/liferea` and the configuration of feeds in `~/.config/liferea`. If you ensure that both directories are transferred to your new system nothing will get list.

In Linux in general always backup your whole $HOME directory and restore it on a new computer to not loose personal data.

**Comment by nekohayo** [comment]
Additionally, Liferea also has the OPML export/import feature in its menus, presuming it is still there. But the method above (preserving your home directory's files) is much better.

As the question has been answered, I would suggest closing this ticket.

**Comment by sjehuda** [comment]
I suppose it is possible to make use of OPML with the entry id as a metadata, yet only for entries that still exist on server..

Or perhaps store the entries in OPML too which would make the OPML substantially larger, or a CSV file, because I think this is a special use case.

@bungadrum, I suggest to use a bookmarks database instead. I use [jarun/buku](https://github.com/jarun/buku).

**Comment by lwindolf** [comment]
I just found out that we have another easier way:

1. you need a search folder that matches all flagged items (as the default "Important" search folder)
2. right click it and select "Export Items to File"
3. transfer the resulting RSS file to your target setup
4. drag and drop the file into your new Liferea setup
