### ISSUE TITLE
Semver and enclosures

### ISSUE THREAD

**Issue by jwmwalrus** [lwindolf/liferea#1373]
Hi.

Does liferea follow semver?

I just upgraded my Debian Testing machine, and liferea went from `1.15.6` to `1.15.7` and the `Ctrl+o` functionality (enclosures) seems to have been removed, which seems surprising from the versioning pov.

Is there an equivalent functionality for that?

**Comment by lwindolf** [comment]
It is correct and intentional for Ctrl+o being removed with 1.15.7. The reason being the change of the enclosure handling to HTML embedding.

Regarding semver: I consider the 1.15 a development branch which is for introducing breaking changes. Due to the slow development cycle some distros decided to use this unstable releases for stable ones. This introduces the problem you get. From upstream pov this breaking change will only be introduced in the stable releases with 1.16.0

**Comment by jwmwalrus** [comment]
Oh, so the versioning follows what Linux 2.6.x and GNOME used to do (even for stable, odd for development). Got it.

That's what I get for using the testing channel of a distro, hehehe.

Thanks for the reply.
