### ISSUE TITLE
malformed HTML in a description gives error "This item has no link specified" on that entry and later ones

### ISSUE THREAD

**Issue by jheidemann** [lwindolf/liferea#1395]
Problem: if a description has HTML in it that is malformed
(for example, an html a link is has its closing /a that is missing its
slash, so it is never closed), then that RSS entry and subsequent ones
show the error "This item has no link specified!",
even though all blog entries have a link element.

Expected behavior: liferea should tolerate malformed HTML because the
world is an imperfect place.

Actual behavior: a broken close anchor breaks links in that RSS entry and
subsequent ones in the feed.

It's not my blog, but I've asked the blog author if I can upload a
minimal sample.  (Or contact me and I can share the test case non-publicly.)

**Comment by lwindolf** [comment]
Without knowing the actual RSS I can only say the following

- RSS is a machine readable format, which needs to be well-formed XML
- what you describe is a use case that sounds like non-well-formed XML or embedded non-well-formed HTML
- XML was designed so that clients do never accept non-well-formed XML
- Liferea still tries to parse broken XML in a best effort manner, but the result is not guaranteed

What Liferea does it relies on an underlying XML parser library libxml2 (which behaviour we cannot change). This library tries to recover from parser failures. What you get for the feed in question is what this library can "restore" of the feeds content.

I consider both the behaviour of libxml2 and Liferea as correct. This issue won't fix.

**Comment by jheidemann** [comment]
The blog was https://www.cs.columbia.edu/~smb/blog/control/blog.xml
(I got SM's permission to link to it).

Unfortunately I lost the original failing code.

He has since fixed the HTML error.  In fact, in the current version it rewrites greater-than and less-than symbols with their html escape codes (ampersand g t semicolon, etc.).  He BOTH fixed the missing /, and by rewriting with escape codes, I would think the bug wouldn't matter now.

@lwindolf: it's your call if you want to insist on correct input or not.   If you're using a 3rd party library I can see how you don't want to wade into that.  (I'm just saying: humans sometimes write html.  Humans make typos.)

If it's really wontfix, I suppose you should close the ticket.

**Comment by sjehuda** [comment]
OFF TOPIC

---

@jheidemann

Please correct the following HTML code:
```
  <link rel="alternate" type="application/rss+xml" href="https://ant.isi.edu/BLOG/atom.xml" />
```

The correct URL:
```
https://ant.isi.edu/~johnh/BLOG/atom.xml
```

Your journal has been added to the [Syndikate](https://github.com/lwindolf/liferea/discussions/1393) database.

---

OFF TOPIC
