### ISSUE TITLE
[Feature Request] Recursive Poperties Dialog (Folder)

### ISSUE THREAD

**Issue by GreenLunar** [lwindolf/liferea#166]
Usability.

I would like to have a Recursive Properties Dialog for folders.
There is a website with advertisement entries which I am subscribed to in Liferea, and a script that filters advertisements entries. I have over 30 subscriptions of this website.
Instead of opening Properties Dialog for 30 times, I would like to open a Recursive Properties Dialog that would apply the same properties to all subscriptions of/under a selected folder.

This feature is essential.

**Comment by lwindolf** [comment]
Please contribute the feature!!!

**Comment by GreenLunar** [comment]
I think this feature is a must and this issue should remain open and be marked under help-wanted.

**Comment by GreenLunar** [comment]
@mozbugbox, does this issue matters to you enough to write a patch to solve it?

I apologies for this direct approach of me to you.

**Comment by mozbugbox** [comment]
I was actually thinking to write a plugin to batch changing feed properties sometime.

**Comment by mozbugbox** [comment]
I've taken a closer look at doing this as a plugin. It's not really possible with the current python binding. The nodePtr, Subscription, updateOptions and a few other `struct` are not really GObject and cannot be freely access from the python side with gobject introspection.

**Comment by GreenLunar** [comment]
How difficult would it be to add this feature built-in (in C language) to Liferea?

In concern to UI:
 **Feed Name** should be **Folder Name**.
 **Feed Source** section should not be.
 Anything else remains as is.

**Comment by lwindolf** [comment]
I guess the preferences dialog code would have to be refactored to be modular and the response callback to work with multiple targets.

A similar problem affects the node sources who actually share some preferences with feeds, but those cannot be changed right now, because the dialog cannot be shown "reduced".

**Comment by mozbugbox** [comment]
It's harder than it sound because a few things have to be done differently. On the other hands, a lot of idea can be copied.

Anyway, I took a stab on it and the result is at mozbugbox/liferea@be55ab06817407f6e29eeff4937d949c1fb319b4.

Only limited test were done. Consider the code alpha quality. Could corrupt subscription database, leak memory, crash... The usual suspects. Use it at your own risk :wink:

**Comment by GreenLunar** [comment]
I think, this issue should be reopened, since there is a patch, though, maybe, not stable.

**Comment by GreenLunar** [comment]
Please reopen this issue.

**Comment by GreenLunar** [comment]
@mozbugbox do you have any news on this?

**Comment by GreenLunar** [comment]
Since a patch was made, may this issue be reopened with a "help-wanted" label?

**Comment by lwindolf** [comment]
@GreenLunar good idea.
