### ISSUE TITLE
Corrupted tray icon under GNOME 3.16

### ISSUE THREAD

**Issue by DoctorJellyface** [lwindolf/liferea#177]
Right now it looks like this:
![snimka obrazovky z 2015-04-15 19-00-53](https://cloud.githubusercontent.com/assets/7472425/7164635/ca9c4c5e-e3a1-11e4-9b9e-075f971c697d.png)

**Comment by DoctorJellyface** [comment]
Also, it seems to draw the icon over itself a couple of times, if Liferea is open for some while.
![snimka obrazovky z 2015-04-20 15-45-50](https://cloud.githubusercontent.com/assets/7472425/7231212/5f052fe8-e774-11e4-90b5-2b31667857bc.png)

**Comment by lwindolf** [comment]
Will try to reproduce this.

**Comment by agilob** [comment]
Very similar on plasma5

![screenshot_20160102_221311](https://cloud.githubusercontent.com/assets/2544251/12076106/b16c3876-b195-11e5-9103-9adeb1ffd596.png)
The one in the middle is liferea.

**Comment by flyser** [comment]
The plasma 5 behaviour is due to https://bugs.kde.org/show_bug.cgi?id=355919
Would it be possible to draw the trayicon without transparent borders?

**Comment by gregorydk** [comment]
This is a "me too"-post.

On GNOME 3.20 in legacy tray.

![screenshot liferea tray 2016-05-06](https://cloud.githubusercontent.com/assets/7804464/15069543/942dd698-137e-11e6-906f-188f8122d28a.png)

**Comment by lwindolf** [comment]
@Leiaz @DoctorJellyface @agilob @flyser @gregorydk Please help retesting the solution in git master!

**Comment by Leiaz** [comment]
Here is what it looks like in Xfce Notification area with "Maximum icon size" set to 23 : 
![liferea_tray](https://cloud.githubusercontent.com/assets/4459071/16170729/2eeb4e04-355d-11e6-8974-0444f1c7f4c4.png)

There is a weird line on the bottom, but it doesn't appear at all sizes. Otherwise it resizes correctly, the repeating image problem is fixed.

Also, this is subjective but I think the `unread.png` icon looks better than `available.png`. The `available.png` icon looks a bit blurry to me, and appear to have a black border around the globe (probably the shadow).

All the plugins were also deactivated at the start for me, so the window was hidden, with no tray icon.
