### ISSUE TITLE
Suggestion: move feed sources into plugins

### ISSUE THREAD

**Issue by dmison** [lwindolf/liferea#186]
I think they would be much easier for most people to implement these as plugins in Python than in C (IMHO)

It would also move the development of feed source support outside of the main codebase.  It would be easier then to support more sources without it being a drain on main development.

**Comment by lwindolf** [comment]
I wholeheartedly do agree!

As always the problem is the history of the code. All non-GObject tightly coupled C-interfaces that cannot be automatically be exposed in GObject Introspection. This currently prevents this really good idea.

There was already one try doing this and we found so many dependencies that cause rewrites in the src/fl_sources/node_source.h interface that we gave up for the moment. The idea is to step by step expose the necessary code.

Are you interested in working on this topic?
