### ISSUE TITLE
No way to select a default download location

### ISSUE THREAD

**Issue by brian-in-crawford** [lwindolf/liferea#195]
This is with version 1.10.12 of Liferea as available from the Debian Jessie repositories. The help file specifically mentions that it may be useful to set a default download directory if you're using Liferea to collect podcasts, and that's exactly what I want to do. It worked just fine with the version of Liferea which used wget and was in the Debian Wheezy repositories, but in version 1.10.12, while I can switch between steadyflow, gwget and kget as the download agent, the box shown in the help as being underneath the dropdown to select the download agent simply *does not exist*. There's nothing there. I'll happily provide a screenshot if needed. The result of this is that everythng ends up on the desktop, and I'm presented with a confirmation dialog for every single podcast. This surely can't be by design? The old version was a superb program, worked exactly as I wanted it to do, but this change and apparent inability to select a default location for the files has made Liferea almost unusable. I hope I'm doing something really stupid and missing something, but I've been back and forth through the menus a dozen or more times, and I simply can't see it. Can we PLEASE have the ability to select that default location implemented for the (64-bit?) Linux version of the program?

**Comment by lwindolf** [comment]
Thank you for reporting this. This is a documentation bug (referring to an option that does not exist anymore).

The reason for switching to a loose coupling with external GUI downloaders only was simply complexity. Due to the nature of different external downloaders not exposing an interface to set the download location and the necessity not to support a different interface for each, Liferea cannot provide default location.

I believe all GUI downloaders should download to the desktop environment download location (usually ~/Downloads) or provide an own persistent way of setting the download location.

**Comment by brian-in-crawford** [comment]
OK, thanks for the explanation. Downloading to the Desktop would not be a problem in itself, it's more the need to acknowledge the save dialog for every podcast that's downloaded which is a showstopper for me. I'm told that gpodder provides the facilities I'm looking for, so I'll give that a try. Thanks for your efforts with Liferea - it worked well for me up to and including the version distributed in the Debian 7 repositories.
