### ISSUE TITLE
Show updated feeds as plain pop-ups containing the entire articles' titles for three seconds for each feed

### ISSUE THREAD

**Issue by birdie-github** [lwindolf/liferea#322]
The current way of showing new articles is beyond unusable: I can only see which feeds have received new articles, yet I don't see the articles' titles. If the user is subscribed to +100 feeds that means he has to open Liferea all the time to check the actual new articles' titles. Clicking "Show Details" from a pop-up is not an option when you have many updated feeds. Too much clicking. Too much messing around for such a simple task as beeing up to date.

It's a huge usability problem - it's not a feature request.

**Comment by lwindolf** [comment]
The use case Liferea implements is reading news in an email like interface in the main window.

The popups are intended for users with few feeds that want to receive sparse notifications.

The use case you describe +100 feeds an per article notifications (meaning up to hundreds of new articles notifying) doesn't make sense to me and is not the use case Liferea implements right now.

**Comment by birdie-github** [comment]
All e-mail applications show **e-mails' subjects** as pop-ups.

What Liferea does is basically showing Senders which brings next to zero information as to whether you should be interested/alerted or not. Run Akregator and compare how Liferea presents new articles and how Akregator does.

With Akregator you immediately know whether new articles warrant attention. With Liferea you have to click/open main window.

And my use case is quite normal: most people who I know are subscribed to at least 40 RSS feeds and most of them bring at least 20 new articles a day. The way Liferea works makes this application 100% counter productive.

**Comment by lwindolf** [comment]
I do agree on some points. I believe the notification plugin should be adaptive and relayout according to the number of new headlines. Something like this schema:

- less than 15 and less then 5 per feed feeds: show feed title + headlines for each feed
- more than 15: no headlines, only feed titles
- truncate feed titles to newest at > 10 feeds

For Liferea the problem is that roughly 30% of the users global update on startup and we had article head lines in the past. Which created a huge mess if you have say 50 feeds and just started up your feed reader after 3 days no reading. You get like 3 minutes of libnotify popups wasting your desktop :-)

So without a complex logic, there is no headline showing possible for the supported Liferea use cases. And so far noone took the plugin and implemented it. I sadly don't have the time right now.

**Comment by GreenLunar** [comment]
This seems complex.  I do like the idea.
