### ISSUE TITLE
liferea crashed with SIGSEGV in operator->()

### ISSUE THREAD

**Issue by paulgevers** [lwindolf/liferea#327]
May I point you to the crash report¹ of liferea in Ubuntu in the hope that it may help you to improve liferea. Please let me know if you believe or suspect this may be Ubuntu/Debian specific.

¹ https://bugs.launchpad.net/ubuntu/+source/liferea/+bug/1560383

"""
Seems I’ve made it run out of memory with three open tabs…
"""

StacktraceTop:
 operator-> (this=0xffffffff) at ../Source/JavaScriptCore/runtime/WriteBarrier.h:123
 isString (this=0xffffffff) at ../Source/JavaScriptCore/runtime/JSCellInlines.h:124
 JSC::JSCell::toPrimitive (this=0xffffffff, exec=exec@entry=0x7f6567b7fb58, preferredType=preferredType@entry=JSC::PreferString) at ../Source/JavaScriptCore/runtime/JSCell.cpp:128
 JSC::JSValue::toStringSlowCase (this=<optimized out>, exec=0x7f6567b7fb58) at ../Source/JavaScriptCore/runtime/JSCJSValue.cpp:312
 JSC::getByVal (exec=0x7f6567b7fb58, baseValue=..., subscript=..., returnAddress=...) at ../Source/JavaScriptCore/jit/JITOperations.cpp:1383

**Comment by paulgevers** [comment]
@lwindolf

Then I suggest you close this bug. I will reassign the bug in Ubuntu to
the package that provides webkitgtk+.

Paul

**Comment by rich-coe** [comment]
I have found numerous crashes in the javascript rendering of webkit of different web pages.
This mainly because the webkit1 version used by liferea is no longer under active development. 
@Leiaz in issue #311 has created a port of liferea to webkit2.   I've been using it for about 3 weeks now. 
I've had very few issues.  One side effect of webkit2 is because it's running in a separate process, if webkit crashes, it no longer crashes liferea.
