### ISSUE TITLE
Video crashes liferea

### ISSUE THREAD

**Issue by marciosr** [lwindolf/liferea#341]
When I open a news that have a video, liferea crashes even without playing it.

Using Arch Linux, with liferea 1.10.17

[lifereabt.txt](https://github.com/lwindolf/liferea/files/239678/lifereabt.txt)
[packages.txt](https://github.com/lwindolf/liferea/files/239682/packages.txt)
[lspci.txt](https://github.com/lwindolf/liferea/files/239683/lspci.txt)

**Comment by rich-coe** [comment]
It's crashing in the video driver vdpau (for amd chipset) on Floating Point Exception. 
If you load the debug package for your video driver, the traceback will make more sense. 
I found this patch for debian http://lists.alioth.debian.org/pipermail/pkg-multimedia-commits/2014-June/050176.html which discusses a similar issue, but I'm not sure how that is related to your problem.
With a valid traceback, it will make more sense when doing a websearch to know which function the problem is actually occurring in.
The other option is to see if there any updates for the vdpau package from your distribution.

**Comment by lwindolf** [comment]
@marciosr Thank you for reporting this. The backtrace indicates the crash is very deep within gstreamer. There is little chance to fix this in Liferea.
