### ISSUE TITLE
'"Last_subscription" updated...' in status bar

### ISSUE THREAD

**Issue by xomrk** [lwindolf/liferea#343]
First of all, I love Liferea! Fast, easy-to-use, cross-platform. TY!
A small issue that makes its usage slightly inconvenient: after I press 'Update all' I see  ''"Last_subscription" updated...' in a status bar. And the real 'Last_subscription' name is different from time to time.
So, it is not easy to understand when it actually finished to update all subscriptions.
Is it possible to show message 'All subscriptions updated' or just to clear the status bar?

**Comment by xomrk** [comment]
SRY, I think that I should post this thread to pull requests. Please, move or remove it.
Great app anyway, TY!

**Comment by lwindolf** [comment]
I agree that this is a usability bug. I thought many times about a solution with the given code base. Problem is that there is no transaction concept to know when the batch update is completed. One reason is that feeds are updated using multiple worker threads and some feeds might be hanging while totally different feeds start auto-updating due to the auto-update interval. Depending on the number of feeds + a short update interval Liferea might be constantly updating stuff.

What do you think about rather having a decreasing count displayed like

"Updating 15 subscriptions..."  (when you click "Update All" and 15 subscriptions are affected)
"Updating 12 subscriptions..."
"Updating 7 subscriptions..."
"Updating 1 subscription..."
"Updating 1 subscription..."
"Updating 1 subscription..." (could be hanging)
<empty status bar> (once all finished)

**Comment by lwindolf** [comment]
Here is how the implemented solution looks like

![update-counter](https://user-images.githubusercontent.com/3315368/103486591-3c623380-4dff-11eb-92fc-86b343ed6264.gif)

**Comment by nekohayo** [comment]
Eh, I guess that works, although it is slightly strange to have a decreasing counter rather than an increasing one ("Updating feed %d of %d..."); also, I still believe the contents of the statusbar would be better suited, in the long term, to being in the titlebar (in the traditional UI) or the headerbar's sub-text (and leaving the hyperlinks to GtkTooltip rather than the statusbar), and thus being able to eliminate the statusbar entirely as proposed in #411... I posted a new comment there with some screenshots of what it could look like, if you'd like to consider that possibility.

**Comment by lwindolf** [comment]
You are right raising number might make much more sense. Will change it accordingly.

About not having a statusbar: yes this might make sense, still I want to solve this first.

**Comment by nekohayo** [comment]
Hi Lars, from what I can see in 1.13.5, can we reopen this ticket for the fact that during a mass update, it not only shows the "Updating %d / %d" status, but also each and every "%s updated..." in the statusbar, which means that the actual counter doesn't get seen much (depending on performance/network conditions) because in my case it gets overridden by the "%s updated" strings, so only _sometimes_ can I briefly see the actual count. But when there is a count, I don't really care to see individual feed names (when undergoing a mass update) so I'd suggest _just_ showing the count in that case.

**Comment by lwindolf** [comment]
Sounds like there is a leftover message from the old code. Just needs to be removed.

**Comment by sunwire** [comment]
> Sounds like there is a leftover message from the old code. Just needs to be removed.

I think that's the code
https://github.com/lwindolf/liferea/blob/505852d2a82b53400715b6f60da9872f9e42f000/src/feed.c#L351-L357
