### ISSUE TITLE
Ability to filter by source

### ISSUE THREAD

**Issue by jochenberger** [lwindolf/liferea#35]
I have multiple subscriptions, some of them added directly, some contained in a tt-rss source. I'd like to create two filters, one that shows me the unread items from from the direct subscriptions and one that shows me the unread items from the tt-rss source.
One way to accomplish that would be a filter criterion that filters on the source (with an option to select something like "No source")

**Comment by lwindolf** [comment]
Did you try using the root node of the source for reading? Because with "hide read items" activated it behaves exactly like this. If you additionally group all other subscriptions into a folder you can read all other (non-source) items the same way.

As this is already possible using folders / the source root node + "hide read items" I think we should not add an additional ssearch folder rule.

**Comment by jochenberger** [comment]
I like to keep "hide read items" disabled, so it's not a complete solution, but I guess I can live with it the way it is. Maybe "hide read items" could be added to the toolbar or the menu and assigned a shortcut? Should I open another issue for that?

**Comment by lwindolf** [comment]
@jochenberger No feature requests please!

**Comment by jochenberger** [comment]
Err, alright, thanks.
