### ISSUE TITLE
segfault when reading rss feed

### ISSUE THREAD

**Issue by Hairybiker** [lwindolf/liferea#372]
When trying to open the BC comic (http://feedproxy.google.com/uclick/bc?format=xml) it crashes every time.

[core.txt](https://github.com/lwindolf/liferea/files/414916/core.txt)
[debug.txt](https://github.com/lwindolf/liferea/files/414918/debug.txt)
[core dump](https://dl.dropboxusercontent.com/u/1458849/core.tar.7z)

**Comment by Leiaz** [comment]
I managed to reproduce the crash by viewing a comic in Liferea's internal browser with javascript enabled, and scrolling a bit (in your core.txt you aren't giving the correct executable name, so gdb's output isn't very useful). The crash actually happens at : 
```
Thread 1 "liferea" received signal SIGSEGV, Segmentation fault.
0x00007ffff410be50 in JSC::JSCell::getPrimitiveNumber(JSC::ExecState*, double&, JSC::JSValue&) const ()
   from /usr/lib/libjavascriptcoregtk-3.0.so.0
```
So the problem is in WebKit's JavaScriptCore, not Liferea. As a workaround you can disable JavaScript.

WebKit 2 (which will be used in future versions #311) handles that amount of dynamic ads much better (although I didn't let the page run for very long ..).

**Comment by Hairybiker** [comment]
Thanks that fixed it. It's the only one I have that downloads the whole web page rather than the just the comic.
