### ISSUE TITLE
When installed to a non-standard directory, liferea crashes with a gsettings error.

### ISSUE THREAD

**Issue by hugomg** [lwindolf/liferea#376]
I recently tried telling the configure script to install Liferea to a non-standard prefix to be able to test run the latest liferea version from the master branch without messing up with the version from my package manager.

    ./configure --prefix=/tmp/liferea-testliferea
    make
    make install

However, when I tried running liferea it crashed with a gsettings-related error:

    (liferea:25208): GLib-GIO-ERROR **: Settings schema 'net.sf.liferea' does not contain a key named 'do-not-track'
    fish: “/tmp/lifereatest/bin/liferea” terminated by signal SIGTRAP (Trace or breakpoint trap)

I found a workaround by changing the XDG_DATA_DIRS environment variable:

     env XDG_DATA_DIRS="/tmp/liferea-test/share:$XDG_DATA_DIRS" /tmp/liferea-test/bin/liferea

However, this is not ideal. The configure script should prepare things so that installing in a different location works without requiring to user to change environment variables.

**Comment by Leiaz** [comment]
This is inconvenient, but I don't think it is a bug.

Applications don't load schemas by their path on the filesystem but by schema id. [GSettings is supposed to look for schemas in XDG_DATA_DIRS by design](https://developer.gnome.org/gio/stable/glib-compile-schemas.html), so changing that variable is the correct way to setup your test environment.

There is [a way to search for schemas in a given directory](https://developer.gnome.org/gio/stable/gio-GSettingsSchema-GSettingsSchemaSource.html#g-settings-schema-source-new-from-directory), but according to the doc it is meant to be used by plugins, not in the general case.

**Comment by lwindolf** [comment]
@Leiaz Thanks for the details here! Make sense in a way.

@hugomg I hope you do not mind leaving this as it is. I added a hint in the README.md on this topic describing you solution and will also blog about it to spread the word.
