### ISSUE TITLE
[Web Integration] Send by Email...

### ISSUE THREAD

**Issue by GreenLunar** [lwindolf/liferea#387]
_'"With Liferea, I have found a new job position which seems to fit well for my brother, but I had to manually copy and paste the entry information."'_

Add integration with Email client software, so that users would be able to send news entries by email, with just a click.

Since no [Type=WebApp](https://lists.freedesktop.org/archives/xdg/2016-February/013679.html) nor an [extended Type=Link](https://bugs.freedesktop.org/show_bug.cgi?id=94191) is yet implemented, adding email integration might require special entries to so called "web-mail" providers, which some we already know.

This might get to be relevant to #131

**Comment by lwindolf** [comment]
Such a feature can be done using "xdg-email" which opens the desktop environments default email client.

**Comment by lwindolf** [comment]
To implement it one could add a headline context + main menu option which takes the headline link and title and runs xdg-email with it.

**Comment by lwindolf** [comment]
Feature was implemented with 1.13.0 (see #680)

**Comment by pabs3** [comment]
@lwindolf please reopen this issue since:

The feature implemented in #680 only shows up when the feed item has an
author field and sends a mail to the author of the entry (and is
missing when creator is used instead), but the feature proposed here is
for sharing the article with someone other than the article author,
similar to the "Bookmark at" feature but with email instead of the web.

**Comment by lwindolf** [comment]
Ah I see. Reopened.

**Comment by pabs3** [comment]
Thanks for that. Probably the functions from that other PR would be
useful to implement this feature request.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by pabs3** [comment]
@lwindolf please reopen this issue since:

The feature implemented in #680 only shows up when the feed item has an
author field and sends a mail to the author of the entry (and is
missing when creator is used instead), but the feature proposed here is
for sharing the article with someone other than the article author,
similar to the "Bookmark at" feature but with email instead of the web.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by lwindolf** [comment]
@pabs3 Ticket was already reopened.

**Comment by pabs3** [comment]
It seems like GitHub re-sent or delayed comments sent by email, sorry for the noise.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by pabs3** [comment]
I am not seeing a commit for this, was it accidentally closed?
-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by lwindolf** [comment]
This request was not implemented and will not be. Closed due to ticket tracker cleanup.
