### ISSUE TITLE
Crash on startup if you have a proxy configured from an older Liferea version

### ISSUE THREAD

**Issue by siebenmann** [lwindolf/liferea#389]
I just updated to the latest git tip from a git version before webkit2 landed. I had a manual proxy configured, and Liferea crashed on startup in `liferea_htmlview_proxy_changed()` in src/ui/liferea_htmlview.c as it tried to call `->setProxy`, because the setProxy field is now NULL as part of the webkit2 update.

It turns out that no matter what proxy option I pick in Preferences -> Proxy on my old (working) Liferea install, the current git tip crashes here for me on startup. I'm not sure what's going on.

**Comment by Leiaz** [comment]
This is a combination of me thinking this function checked for NULL like the others in the WebKit 2 code (where proxy settings don't have any effect for now) and in fixing proxy settings (with previous WebKit1) always passing the proxy settings to differentiate "default proxy" and "no proxy".

Should be fixed by #391.

**Comment by lwindolf** [comment]
Merged #319.
