### ISSUE TITLE
Tray icon not present on Wayland, Liferea broken after "closing" to tray

### ISSUE THREAD

**Issue by genodeftest** [lwindolf/liferea#461]
Steps to reproduce:
1. run liferea on wayland
2. enable the systray plugin
3. close liferea which should minimize it to tray

What happens:
Liferea's window is gone and you can't get it back from systray because there is no systray icon in wayland. How do you get liferea back?

What should happen:
The design decision of GNOME devs is to not allow tray icons any more. Thus, liferea must not load this plugin on wayland.

Which version:
latest git from today

**Comment by lwindolf** [comment]
I totally agree. The thing is there is AFAIK no such thing as a "desktop detector". I also believe the decision (if possible at all) should not be about Wayland, but about the desktop environment.

**Comment by lwindolf** [comment]
Adding a wayland check to the trayicon plugin could be a solution.

**Comment by Leiaz** [comment]
It is suggested on the doc to use [gtk-status-icon-is-embedded](https://developer.gnome.org/gtk3/stable/GtkStatusIcon.html#gtk-status-icon-is-embedded) to check if the icon is actually in a tray.

**Comment by glaubersm** [comment]
Liferea 1.12.6 also does not show a systray icon on kde plasma 5.15.4 Wayland session.

**Comment by nekohayo** [comment]
I believe the issue is either that this plugin...
* _should not be enabled by default_ (it currently seems to be, which was confusing to me when I launched the app on a brand new computer that doesn't have a tray area; the app silently kept running in the background) _and_ should have a warning in the description, about the side-effects of enabling it if users don't actually have a notification area for the icon to show at?
* ...or should be killed entirely, because [GtkStatusIcon](https://developer.gnome.org/gtk3/stable/GtkStatusIcon.html) is deprecated in GTK _and_ it's hell to manage anyway? (a source of bugs, additional code complexity, unexpected usability problems like the above, etc.). For what it's worth, we removed the notification icon / tray icon / status icon plugin in GTG for such reasons. It's a design pattern that has been phased out and modern tech stacks don't support it.

**Comment by lwindolf** [comment]
I agree the status icon is hell to manage. Nonetheless user base seems large (and I personally believe GNOME is entirely wrong with trying to phase it out). Microsoft for example did great work to solve the tray issues starting with Win10.

As for Liferea: past behaviour was trayicon was delivered with the app and the idea was not to suddenly break workflow/behaviour for people with the trayicon active.

One way would be to not enable the tray plugin in 1.14 for all new users.

**Comment by mhoran** [comment]
The future of tray icons seems to be [Ayatana Indicators](https://ayatanaindicators.github.io/). My understanding is that these should work with GNOME (even on Wayland), KDE, and other X desktops like Cinnamon, MATE, etc. Perhaps the trayicon plugin could be extended to try Ayatana Indicators first and fall back to the legacy GtkStatusIcon. Note that GtkStatusIcon doesn't seem to work on GNOME X sessions anymore, at least on Debian 11.

Ayatana Indicators do behave a bit differently than GtkStatusIcon; there is no `activate` signal; left and right click both bring up the context menu. Otherwise he behavior should be familiar to users.

I do agree that the plugin should probably be disabled by default for new users, since it seems that some of the mainline desktop environments don't provide a tray unless an extension is installed.

**Comment by lwindolf** [comment]
@mhoran Good to know. Surely worth looking into it.

**Comment by heini** [comment]
It's 2022, I run liferea on Plasma/Wayland and have no tray icon. So I asked Google and found this ticket, opened 6(!) years ago...

**Comment by lwindolf** [comment]
@heini Can you elaborate on your expectations? Your comment is not helpful and as such can only serve to frustrate maintainers.

**Comment by heini** [comment]
That's quite simple. FLOSS projects expet users to contribute, be it by adding code or just writing bug reports. But then those bugs don't get fixed, mostly in favour of new features, which introduce new bugs. This issue is such an example. It has been opened 6 years ago, is still not fixed and seems to be the only source of information for the problem.

Well, and this is what frustrates users...

**Comment by lwindolf** [comment]
@heini So you feel entitled to put your frustration here. You probably misread the license which does not talk about such a thing, in the opposite please reread the "AS IS" clause. Thanks!

**Comment by nekohayo** [comment]
Today when testing the new 1.14 release on a new computer, I encountered this issue again, because the "tray icon" plugin is enabled by default, so I was about to report this bug again, until I rediscovered this ticket :)

My suggestion remains the same: please don't enable it by default (and if people enable it, then I guess they're "on their own", until a fix for the 2nd bug here is contributed).

The default gsetting for it should be off, which wouldn't affect existing users who have set it to be enabled. So the `active-plugins` gsetting key should be not be `['gnome-keyring', 'media-player', 'trayicon', 'plugin-installer', 'pane']` by default, it should rather be `['gnome-keyring', 'media-player', 'plugin-installer', 'pane']`, or `['gnome-keyring', 'media-player', 'headerbar', 'plugin-installer', 'pane']` if you want to go for a more modern look by default.
