### ISSUE TITLE
Please add "Select all" feature to itemlist

### ISSUE THREAD

**Issue by genodeftest** [lwindolf/liferea#475]
Currently, there is no way to empty a folder of its news items. I'd like a "Select all" feature in feed item list, preferably with Ctrl+A as keybinding, to select all items.

I'm running 1.12-rc2.

**Comment by rich-coe** [comment]
Does this work for your use-case?
Select folder
Click "Mark Items Read" from top selection bar.

**Comment by genodeftest** [comment]
Thanks for the tip, but unfortunately this doesn't work. I want to delete the news items, I do not care about their read status.

**Comment by rich-coe** [comment]
You do know that feed items that you've read and deleted will come back as unread the next time the feed is updated if they are still listed in the the feed?

**Comment by genodeftest** [comment]
Oh, I didn't know that (yet). That's bad, because it will lead to many megabytes of disk usage. Seems like there is a bug reported for this already: #458

**Comment by rich-coe** [comment]
I think this is would be valuable feature.  My use case is when I've accidentally hit 'mark all read'.  There's no way to revert the change.  You have to click in each item in the list you want and mark them unread.

For your use case, the ideal would be for 'delete' to hide the entry until feed didn't publish it any more, and then delete it from the database.  

I'm not sure how useful deleting objects are because I'm not familiar with how the database allocates space on disk.  I suspect, but do not know, that it grows when it needs to, but doesn't shrink.   Perhaps it's aggressive about collapsing unused space.
