### ISSUE TITLE
enclosures not downloading

### ISSUE THREAD

**Issue by HLHJ** [lwindolf/liferea#477]
I can't get enclosures to do anything other than live-load. When
I am offline, I can't see enclosures, even those I have previously viewed. 

I'm not sure if this is a settings problem. The documentation for enclosure download preferences, available here:
http://lzone.de/liferea/help110/preferences_en.html#enclosures

...does not match the menu in my copy of Liferea 1.10.12-1, downloaded
through the Debian package management system. Specifically, my copy has no
text field for choosing whither to download enclosure files.

I thought that option might have changed to be configurable on a per-feed
basis, since that could actually be quite handy, but I can't see it
anywhere.

I have had a look through the bugs and the list archives; forgive me if
I've missed something obvious.

In case I've been unclear, I'll give an example of what I'm trying to do:
at 3 a.m. daily, I want Liferea to automatically check Xkcd and download
any new comics to a folder somewhere for later reading offline.

**Comment by ahmedelmahy** [comment]
I have the same problem
```
$ liferea --version
Liferea 1.10.17
```

**Comment by JigmeDatse** [comment]
I'm not sure if my problem is the same or similar or not but:

```
$ liferea --version
Liferea 1.12.3
```

And this may be related or not, but I want to provide a bit about what I'm noticing about this.

I have a couple of different enclosures that I've looked at from the Free Music Archive:

https://freemusicarchive.org/music/download/1cadd1bff7cd9120a8e6169618c9dfa8f205ba3a.mp3

Which right now doesn't download, and dumps me to the front page.  

And:  

https://freemusicarchive.org/music/download/1af0d977c33d7ac4d342b0cb13358bf78f50ded4.mp3

Which is downloading, and works as expected.  

Now the thing is with the links which behave like the first one gstreamer reports:

```
Error: gst-core-error-quark: Your GStreamer installation is missing a plug-in. (12) /var/tmp/portage/media-libs/gst-plugins-base-1.12.4/work/gst-plugins-base-1.12.4/gst/playback/gsturidecodebin.c(998): no_more_pads_full (): /GstPlayBin:player/GstURIDecodeBin:uridecodebin1:
no suitable plugins found:
/var/tmp/portage/media-libs/gst-plugins-base-1.12.4/work/gst-plugins-base-1.12.4/gst/playback/gstdecodebin2.c(4600): gst_decode_bin_expose (): /GstPlayBin:player/GstURIDecodeBin:uridecodebin1/GstDecodeBin:decodebin1:
no suitable plugins found:
Missing decoder: text/html (text/html)
```

Which isn't giving a hint (and only shows up when I launch from command line, and it shows there), as to what the problem is.

Though I think that this isn't an easy fix in this case, as it appears the behaviour of Free Music Archive is not such that you can tell why you're not getting the MP3 file.

**Comment by lwindolf** [comment]
@JigmeDatse The Free Music Archiv enclosures suffer from the GDPR confirmation page FMA now servers on any request. It is sadly permanently broken for feed readers.

**Comment by JigmeDatse** [comment]
Thank you for the specific problem I was facing, occasionally it seems to work, but it seems that too many services are breaking because they think there is a better way to do things than how the standards say they should be done.  It's sad, but it is the truth.

**Comment by marciof** [comment]
Answering for my own benefit:

It looks like the [documentation on the enclosure preferences settings may be outdated](https://lzone.de/liferea/help110/preferences_en.html#enclosures).

I tested versions 1.13.1 and 1.13.5 and they both don't have that *"Save downloads in"* setting in the preferences anymore. However each feed subscription has an option in the *"Advanced"* tab to *"Automatically download all enclosures of this feed"*. I don't know when this was first introduced, but that [setting is in code as `feed.encAutoDownload`](https://github.com/lwindolf/liferea/blob/2603ec638c7e0ccfeb01a8e332bf54161ce8804c/src/feed.h#L59).

**Comment by lwindolf** [comment]
@marciof Will update docs to match new naming.

**Comment by lwindolf** [comment]
@marciof Docs updated with 852d5ff4
