### ISSUE TITLE
Clicking any audio attached feed (podcasts) interrupts and resets currently playing audio using in-app audio player

### ISSUE THREAD

**Issue by ghost** [lwindolf/liferea#555]
Currently using a VLC enclosures commandline to handle mpeg that takes it outside the program to get around this.  Very glad this capability is there.

Besides not having any indication where the currently playing episode is at in the treeview, if you click any podcast episode (including the currently playing episode to skip back) it resets the currently playing podcast.

Makes browsing other feeds while playing a podcast using the builtin player pretty risky.  As soon as you leave that episode, you lose the ability to control the podcast stream if you miss something.

Love the aggregation of podcasts with my other RSS feeds.

**Comment by lwindolf** [comment]
I suffer this problem the same way you do. I'm still not sure how to solve it. Do you have any ideas on where to present the media player so that it still indicates music belonging to a current headline and still is able to indicate another music element you are just now playing?

**Comment by ikidd** [comment]
I would just leave the audio stream where it is, and put a speaker icon next to the currently playing feed/episode in the treeview.  But you would need to figure out why the currently running audio stream drops if you hit any item that has an audio attachment.  It's obviously trying to grab the audio stream handle when you enter one of those items but it probably shouldn't until you actually hit Play on a new one.

**Comment by Leiaz** [comment]
I thought the fact that the player keeps existing, and playing, when you leave an item was more an accident than a wanted feature.

Some time ago I refactored the media plugin code a bit (see experimental [enclosure-list-view branch](https://github.com/Leiaz/liferea/commits/enclosure-list-view)) 

> I would just leave the audio stream where it is

The media player widget (play buttons and progress slider) is provided by the Media player plugin and it inserts itself in the EnclosureListView (providing the list of enclosures treeview). It is destroyed if you change view mode or go to a feed in a different view mode. So if it is supposed to stay, for instance when switching to a feed in combined view, it can't really stay where it is.

> put a speaker icon next to the currently playing feed/episode in the treeview

This requires changing the media plugin interface because currently it has no way to tell Liferea what it is playing. The media player plugins only get a list of enclosures (MIME type + url) not the item or feed where it comes from.

> But you would need to figure out why the currently running audio stream drops if you hit any item that has an audio attachment.

There is no mystery here. If you go to an item without audio or video MIME type enclosures, Liferea doesn't call `load` to pass an enclosure list to the plugin. The widget will be hidden along with the EnclosureListView if the item has no other type of enclosure, but the widget keep existing and doing what it was doing. If it gets a new list of enclosures, that list replaces the old one, it is ready to play the first item in that list.

I made the "keep playing" part work in my experimental enclosure-list-view branch linked above. Problem : there is no stop button, so it keeps playing :D I thought it would be weird to have the player go away when merely paused ... I don't know what would be the best way to handle it. Add a stop button, discard when paused, nothing ?

To make it indicate what it is playing, it could have a "entering item" method, called with the item, but for that I think they would need to be introspectable. Then the plugin could also implement the LifereaShellActivatable to mark the playing item/feed in some way.
