### ISSUE TITLE
Make internal browser supply a mobile user agent

### ISSUE THREAD

**Issue by lwindolf** [lwindolf/liferea#571]
To get less heavy-weight content on internal browsing supply a mobile user agent to Webkit per-default (maybe optional for people that do not like it).

Rational: a mobile user agent always almost fetches a more light-weight more-readable, a bit more ad-less website.

**Comment by da2x** [comment]
Nope. Nope. Nope. Don’t lie in the User-Agent. Down that path lies only evil.

Send the [`Save-Data: On` request header](https://www.ctrl.blog/entry/http-save-data) if you want to save data/get a lightweight page. You can even [ask network-manager](https://developer.gnome.org/NetworkManager/1.2/nm-dbus-types.html#NMMetered) if the user is on a metered network (`NM_METERED_YES`) and turn on this header automatically with every web request.

**Comment by Gert-dev** [comment]
I agree that lying in the user agent isn't the proper way to request sites to send more lightweight versions; sites probably shouldn't be using the user agent to detect this, anyhow.

On the other hand, if there is no other way to get (crappy?) sites to serve a better version than spoofing the user agent, I say go for it, since, for the same reason listed above, user agents shouldn't be relevant for modern websites anyway.

An interesting solution may be to simply make the user agent configurable. (Also, FYI, user agents can be used as part of tracking fingerprints.)

**Comment by da2x** [comment]
A crappy site is a crappy site. It’s the site the user has chosen to visit. If the site does a bad job at presenting the content, it’s not Liferea’s job to fix it.

Anyhow, you get non-crappy websites by using Readability. It’s what powers “reading mode” in every browser (except Edge who re-implemented Readability because it wasn’t inveted in Redmond). [Mozilla’s version](https://github.com/mozilla/readability) seems usable.

**Comment by Gert-dev** [comment]
@da2x Agreed, it's not Liferea's job to (try and) fix it and it was the user's explicit choice to subscribe to the RSS feed of said crappy website. However, without Liferea providing the means for the user to fix it themselves, i.e. by allowing the user to change the user agent for each feed, the user has no choice but to leave it as-is (or complain to the website owner). Doing it out-of-the-box sounds like a bad idea, though.

Readability may also be a good fit. It requires JavaScript, however, which would require a specific exclusion from blocking for users that already disable JavaScript in Liferea - or a separate JavaScript processor inside Liferea' code. If it were optional, it would be in the hands of the user again, but with automatic use, Liferea would basically be overriding the formatting present in the feed's posts again, which puts you in the same position as the user agent (i.e. the site should fix its feed's formatting instead of Liferea doing it).

As a side note, Liferea currently also provides conversion filters, which can be used for manipulating and cleaning up feeds, and work really well. They currently provide no way to hook into the original request, though; you only get to hook into the processing stage.

**Comment by lwindolf** [comment]
Readability sound like a good idea. We should evaluate it.

Additionally having a plugin that allows setting "User Agent" alternatives is another good idea. This allows "User Agent" manipulation for all types of reasons (security/getting mobile websites/...)

**Comment by lwindolf** [comment]
With PR #665 we now supply a user agent in the webkit view.
