### ISSUE TITLE
link for ~/.config/liferea/feedlist.opml is not respected by liferea

### ISSUE THREAD

**Issue by DirkSchmitt** [lwindolf/liferea#574]
I tried to link ```~/.config/liferea/feedlist.opml``` via ```ln --symbolic …``` to a different location (under version control). This approach works well for other application, but it is failing for *liferea*.

Here after the next start of *liferea* the symboling link is replaced with a *normal file*.

**Comment by lwindolf** [comment]
This is due to a backup mechanism we have in place. On each startup the OPML file is copied to ~/.config/liferea/feedlist.opml.backup this is to allow users with memory corruption to recover their feeds. If ~/.config/liferea/feedlist.opml is not parseable Liferea will hint on restore the backup file.

And the only 100% safe way of creating the backup file is a move operation :-(

While I totally understand your use case I consider the backup feature more important.

**Comment by DirkSchmitt** [comment]
Sorry - I understand your *motivation*, but not your *solution*.

I suggest you use the *move operation* to be save in case of space exhaustion.
This is true for a *real file* on the **same harddisk**.

But in the case of a *symbolic link* this isn't *true* any more.


My proposal is to check if `feedlist.opml` is a *real file* or a *symbolic link*.
If `feedlist.opml` is a *symbolic link* the whole backup mechanism is skipped, because:
 - A user customisation out of the scope of the liferea application has been done and shouldn't be destroyed.
 - It can't be assured by *move* that the space isn't exhausted.
