### ISSUE TITLE
Asian complex script and font rendering problem. 

### ISSUE THREAD

**Issue by haseebmahmud** [lwindolf/liferea#586]
Hi, 
I just want to report some bugs in showing Bangla scripts in the reader. 

Problem: 1
Complex scripts are not showing correctly. e.g. 
![selection_298](https://user-images.githubusercontent.com/544033/34521633-0e6f9420-f08f-11e7-87c4-d7333a70e2ee.png)

Problem: 2
Font rendering. Look at the underlined words. A dot is missing. The য়'s become য 
![selection_299](https://user-images.githubusercontent.com/544033/34521664-3ab79d0c-f08f-11e7-9c4d-f00b818687bf.png)

The correct rendering should be like this,
![selection_300](https://user-images.githubusercontent.com/544033/34521682-4b6f7afc-f08f-11e7-95ab-020c283ab2d6.png)

Thanks for your good work.

**Comment by lwindolf** [comment]
The difference in the rendering is probably due to two different renderers being used

1. GTK Pango rendering in the feed list
2. WebkitGtk rendering in the headline view

depending on GTK preferences and system defaults there is a certain possibility that both renderers use different fonts too.

You you please open the article that is incorrectly rendering using Epiphany (called "Web" nowadays)? Does the same rendering issue show there too?

**Comment by haseebmahmud** [comment]
@lwindolf Yes. I have just installed the Epiphany/Web browser. I see the same rendering issue in that browser. Chromium and Firefox is working fine.

**Comment by lwindolf** [comment]
In this case you need to submit a bug report against the Webkit project (Apple / Safari) :-(
