### ISSUE TITLE
Internal browser doesn't enforce line break when the line is too long

### ISSUE THREAD

**Issue by TheFrenchGhosty** [lwindolf/liferea#754]
If a line of an entry is longer than the size of the internal browser Liferea will not automatically add a line break and will keep everything in the same line.

![liferea](https://user-images.githubusercontent.com/47571719/66708362-e8bd8300-ed3e-11e9-8f9e-003a6d07e34a.gif)

Feed used in the gif: https://invidio.us/feed/channel/UCSuhUzpdXg9jme6eN6HA_IA

**Comment by lwindolf** [comment]
I can reproduce the effect. It's hard to actually decide if this issue is an actual bug.

What happens is that the feed specifies text using `<p style="white-space: pre">` which means the feed explicitily specifies non-line breaking, which Liferea renders as requested. I totally see why this is a nuisance and probably unintended by the feed author.

As there are valid use-cases for non-breaking lines in feeds marked up as HTML (e.g. items with code examples) I think Liferea should not ignore it. I suggest asking the feed provider to fix the HTML inside the feed.
