### ISSUE TITLE
What is Liferea 1.12.7

### ISSUE THREAD

**Issue by blueray453** [lwindolf/liferea#771]
The [change log](https://github.com/lwindolf/liferea/blob/e930d7b422401a227ec9fc72d26feb42d1f5836b/ChangeLog) says that the version after 1.12.6 is supposed to be 1.13

However there is a [ppa](https://launchpad.net/ubuntu/+source/liferea) in launchpad that is distribution 1.12.7

There is a [guide](http://ubuntuhandbook.org/index.php/2019/08/liferea-1-12-7-released-install-ubuntu-18-04/) to install Liferea 1.12.7 from PPA 

```
sudo add-apt-repository ppa:ubuntuhandbook1/apps
sudo apt-get update
sudo apt-get install liferea
```
What is going on here? Is the ppa method of installing liferea safe? Is there any official ppa?

**Comment by lwindolf** [comment]
There is no official PPA. 

You find the official 1.12.7 release here https://github.com/lwindolf/liferea/releases/tag/untagged-cd45fa8ca1dd0565bba7

In master changelog you only find 1.12.6 because with the start of 1.13 development a 1.12 branch was created which you can find here (including a changelog mentioning 1.12.7) https://github.com/lwindolf/liferea/blob/liferea-1_12/ChangeLog

**Comment by blueray453** [comment]
https://github.com/lwindolf/liferea/releases/tag/untagged-cd45fa8ca1dd0565bba7 seems dead.

**Comment by lwindolf** [comment]
Sorry, I cannot reproduce this. This links loads the 1.12.7 release page for me. Maybe you can try to access it via https://github.com/lwindolf/liferea/releases
