### ISSUE TITLE
make install issue on ubuntu 20.04

### ISSUE THREAD

**Issue by TusharSariya** [lwindolf/liferea#831]
tushar@tushar-desktop:~/Documents/liferea$ make install
Making install in doc
make[1]: Entering directory '/home/tushar/Documents/liferea/doc'
Making install in html
make[2]: Entering directory '/home/tushar/Documents/liferea/doc/html'
make[3]: Entering directory '/home/tushar/Documents/liferea/doc/html'
make[3]: Nothing to be done for 'install-exec-am'.
 /usr/bin/mkdir -p '/usr/local/share/liferea/doc/html'
/usr/bin/mkdir: cannot create directory ‘/usr/local/share/liferea’: Permission denied
make[3]: *** [Makefile:422: install-htmldocDATA] Error 1
make[3]: Leaving directory '/home/tushar/Documents/liferea/doc/html'
make[2]: *** [Makefile:494: install-am] Error 2
make[2]: Leaving directory '/home/tushar/Documents/liferea/doc/html'
make[1]: *** [Makefile:398: install-recursive] Error 1
make[1]: Leaving directory '/home/tushar/Documents/liferea/doc'
make: *** [Makefile:686: install-recursive] Error 1

**Comment by lwindolf** [comment]
Please run

    sudo make install

as default installation target is /usr/local which you need root permissions for!

**Comment by Leiaz** [comment]
And for many people the answer is not even that but rather `sudo apt install liferea`.
I always hesitate on how to answer those questions because I don't want to sound too much like "you don't know what you are doing!", but I have seen multiple new Linux users automatically go to the software webpage to download and install stuff instead of using the package manager ...
Uninstalling and updating is not convenient after a default `sudo make install`.
