### ISSUE TITLE
Build instructions missing a few items

### ISSUE THREAD

**Issue by BillDietrich** [lwindolf/liferea#857]
On Ubuntu GNOME 20.04 at least, the source build instructions in the README are missing a few items: dependencies libtool and intltool, and a "sudo" on "make install".

I would like to fix this issue myself, as practice for submitting some source code changes to the project.  So please don't fix it yourself.

I have used GitHub only for single-person projects without branching.  Is the correct process to create this issue, create a branch, commit changes to the branch, then create a pull request (referencing the open issue) for the branch ?  Then you will evaluate the PR, and if approved, you will merge the branch into the master ?  Thanks.

**Comment by BillDietrich** [comment]
I get an error when trying to push to the branch I created:

```
$ git status
On branch issue857
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   README.md

~/projects/liferea $ git diff
~/projects/liferea $ git commit -a -m 'in build instructions, add dependencies libtool and intltool, and "sudo" on "make install"'
[issue857 4b36e458] in build instructions, add dependencies libtool and intltool, and "sudo" on "make install"
 1 file changed, 4 insertions(+), 4 deletions(-)
~/projects/liferea $ git diff
~/projects/liferea $ git push -u origin issue857
Username for 'https://github.com': BillDietrich
Password for 'https://BillDietrich@github.com': 
remote: Permission to lwindolf/liferea.git denied to BillDietrich.
fatal: unable to access 'https://github.com/lwindolf/liferea.git/': The requested URL returned error: 403
~/projects/liferea $ git status
On branch issue857
nothing to commit, working tree clean
```

**Comment by Leiaz** [comment]
That is because you don't have the right to push to this repository. In order to post a pull request, you must fork it on GitHub, to make your own Liferea repo on GitHub, then you push your branch with your changes on your Liferea repo on GitHub. After that, you can open a pull request and choose your branch. Github will even show a notification to directly open a pull request for that branch when you visit the Liferea repo.

**Comment by BillDietrich** [comment]
Okay, I will do that, thanks.  But that is not the normal method, is it ?  I thought normally people could create a branch without forking a whole repo.  Maybe I'm wrong.

**Comment by Leiaz** [comment]
No, you can only create branches if you have write access to the repo. Making a fork is the normal method on Github, unless you have write access to the repo.

**Comment by BillDietrich** [comment]
Okay, let me see if I have this straight:
1- I fork the whole Liferea repo to make my own repo
2- I create a branch off my own repo
3- I make the changes in that branch and push the branch to my repo
4- I don't merge the branch into my repo
5- I create a PR on the Liferea repo, referring to the branch on my repo
6- If you approve, you merge the branch from my repo into the Liferea repo
Do I have that right ?  Thanks.

**Comment by Leiaz** [comment]
Yes, that is correct.

About 2 and 3, unless you edit directly on Github there are 3 git repo involved : the one on your computer, your Liferea copy on Github and the Liferea repo. It looks like you already have your branch with your changes. You currently have Liferea repo as the `origin` remote. You can add your Github repo to the list of remote repo : `git remote add myfork git@github.com:BillDietrich/liferea.git`
And then you `git push myfork mybranch`.

About 4 and branches : you could push your changes on top of your repo's master branch, or merge your branch in your own repo's master branch if you wanted to. You could still post a pull request of the changes between your master branch and the Liferea master branch. It is just more convenient to have the master branch of the local repo track Liferea's original master branch, because other changes could be pushed to it before your changes are accepted and then your master branch would diverge from Liferea's ...

**Comment by BillDietrich** [comment]
Sorry, still confused.  I push changes to my (non-master) branch of my repo.  How do I "have the master branch of the local repo track Liferea's original master branch" ?  By "local repo" do you mean the files on my local disk, or the files in my repo on GitHub ?  The files on my disk are not a repo, they are a clone of a repo on GitHub.

Do I or don't I merge my (non-master) branch into my master in my repo ?  Then the PR I file on the Liferea repo refers to my non-master branch or my master ?

This all is FAR more confusing than I thought it would be.  I didn't think this is what forking was for.

**Comment by Leiaz** [comment]
So, first, your steps to post a pull request were absolutely correct. I just wanted to clarify how it works.

> By "local repo" do you mean the files on my local disk, or the files in my repo on GitHub ? The files on my disk are not a repo, they are a clone of a repo on GitHub.

The files on your disk are a repository too. This is what is great with the distributed nature of git. You can clone it and push and pull from it too, although if you want to do it from another machine, you would have to setup a server first to access it. 

> Sorry, still confused. I push changes to my (non-master) branch of my repo. How do I "have the master branch of the local repo track Liferea's original master branch" ? 

If you cloned your local repository from Liferea's repository, your local repository is set to push, pull from it by default. The "origin" remote is Liferea's repo, because this is the one you cloned from. The master branch of the repo on your disk is set to track "origin/master", so that when you do a `git pull` when on the local master branch, it will pull changes from Liferea's master branch, without passing any argument. The status command will also tell you whether this branch is up to date with the branch it was set to track.
```
git status                
On branch master
Your branch is up to date with 'origin/master'.
```
The master branch on the repo on your disk doesn't have to be identical to the other master branches in the other repo. *But* it more convenient, in my view, if the local master branch is kept identical to Liferea's master branch.

If you haven't yet, look at The [Pro Git](https://www.git-scm.com/book/en/v2) book, it has more complete explanations of how branches work.

> 
> Do I or don't I merge my (non-master) branch into my master in my repo ? Then the PR I file on the Liferea repo refers to my non-master branch or my master ?

No, don't merge your branch. What I meant is : it doesn't matter, you can open a pull request between Liferea's master and your issue branch in your Github repo or between Liferea's master and your master branch (in your Github repo).

> 
> This all is FAR more confusing than I thought it would be. I didn't think this is what forking was for.

"Forking" is just Github's name for making your own clone of someone else's repo on Github. It is a weird name and completely different from forking an open source project (into a new project).

**Comment by BillDietrich** [comment]
Not sure how I should cross-link these things.  Here is link to the pull request: https://github.com/lwindolf/liferea/pull/858
