### ISSUE TITLE
Implement "Automatic" option for view mode

### ISSUE THREAD

**Issue by lwindolf** [lwindolf/liferea#889]
There should be a new view mode automatically switching between "Normal View" and "Wide View" based on the aspect ratio of the application window.

Maybe we should also drop the per-feed view mode preference as it has quite bad usability (unclear what will happen in which switching circumstance) and would become even more confusing with automatic mode.

Note that the aspect ratio has to be considered relativ to the screen aspect ratio (e.g. a laptop flipped to the side).

**Comment by nekohayo** [comment]
An alternative could be to make the wide view mode the "One Mode to Rule Them All", as per the idea in https://github.com/lwindolf/liferea/issues/534#issuecomment-757546005 where you can see this mock-up showing a variant that is adapted both for low-width resolution screens as well as split screens or wide screens (someone reading on an ultra-wide screen is probably half-tiling or third-tiling Liferea or keeping it as a window, anyway):

![liferea new old wide view mockup](https://user-images.githubusercontent.com/479401/104136534-dd537000-5364-11eb-8a97-bf104044b51d.png)

The advantage of that one-size-fits-all approach is _massively_ simpler code and solves a bunch of usability issues. You could even do the switch between two-columns and three-columns layout dynamically depending on the window's width (i.e. available space), which would be in the same spirit as your "automatic" view mode idea here, and the code to do that on the fly (if you prefer not to have it as an option) would probably be trivial even without using LibHandy.

**Comment by antistress** [comment]
Hi,
I own a LCD 19" 5:4 screen and the above mockup will fit my needs !
Thanks

**Comment by lwindolf** [comment]
Well while it looks a bit unexpected (there are only a few newsreaders using this layout) it works well on

- 4:3 and similar aspects
- in non-fullscreen windows mode
- in half-screen mode on 16:9 and similar aspects

it would behave worst on 16:9 full screen where wide view is currently the best mode.

**Comment by nekohayo** [comment]
Yeah, as I suggested above, in full-width-16:9 high-resolution (i.e. full HD) screens, the three-columns layout could still automatically be used. My proposal was:
* 2-columns variant when width is constrained
* 3-columns when there's a ton of width going unused
* dynamically switch between the two layouts depending on window width (i.e. when >=1600px? or >= 1920px?)

In theory it's just a matter of detaching (i.e. gtk_container_remove or the equivalent derivative?) widgets out of some panes/boxes and moving/reattaching them (gtk_container_add or the equivalent derivative?) to different panes/boxes, _not_ using "different widgets" like what's currently done now in normal vs wide view modes; notice how my screenshot above uses the listview from the current "Normal view" mode, because the two-columns view allows ensuring the list of items inside a feed always has sufficient width to be usable at lower resolutions without a multi-line-per-rows listview variant (like what we currently have in the "Wide view" mode)...  thus the massive code simplification.

I think it would work well on any computer screen (not on a phone, but that's another kind of thing, where you'd essentially have to use a "paged view" kind of thing, which is beyond the scope of this simple improvement suggestion here); so I'm not sure there are "use cases to prefer" since it simply adapts to whatever width is available to stay readable. We can have our cake and eat it too.

**Comment by nekohayo** [comment]
Quoting myself:
> The only caveat I can imagine is if some people actually prefer the "normal view" for some other reasons

...and now it occurred to me that the proposed auto-2-vs-3-columns approach above doesn't even need to mean that the "normal view" gets deprecated entirely, it can be kept too at virtually no cost (in case you want to play it safe with the userbase). It just means that the "wide view" gets an automatically adapted layout _and_ that it uses the same widgets as the normal view, so the code simplification gains are still very real, even if you still offer both the "normal" view and the "wide" view (which, at this point, I would rename "Classic" vs "Modern/Adaptive" and set the default to the new adaptive view, because the normal view isn't really the norm anymore)

**Comment by lwindolf** [comment]
Using the same widget sounds tantalizing from a maintenance perspective. I need to sleep on this some more, but it sounds like something to consider.

**Comment by lwindolf** [comment]
Thinking some time about this: I really like it and want to try it out.

In best case we when doing this we could
- drop any preferences on view mode
- drop feed specific view mode
- just switch automatically based on window size ratio
- maybe have hidden dconf ratio switch for users not liking it
- even allowing for a plugin to move widgets to make it look like old email mode

**Comment by lwindolf** [comment]
Started implementation. For now removed per-node layout setting and main menu view mode switches. Only view mode preference remains.

**Comment by lwindolf** [comment]
Implemented.
