### ISSUE TITLE
In 1.13.3, window width and height are not restored on startup if the window is not maximized and the headerbar plugin is active

### ISSUE THREAD

**Issue by nekohayo** [lwindolf/liferea#909]
My Fedora computers jumped from 1.12.x to 1.13.3, in which I discovered a regression: while the window width and height are correctly saved in gsettings/dconf on app shutdown, when you launch Liferea again, if the "last-window-maximized" == false, then it will fail to set the width and height from the values of last-window-width and last-window-height, resulting in a Liferea window that is systematically set at 640x480* on startup. This wasn't a problem before.

*: by the way, 640x480 is a bit ridiculous as a default fallback value in this day and age; 1000x550 (to approximate 1024x600 (the lowest resolution you can expect nowadays, even if it was a netbook from 2009) would be more appropriate. Otherwise you are sizing the app to be unhelpful by default, which is a common app design "blooper".

**Comment by Leiaz** [comment]
Are you using the header bar plugin ? Do you have the issue without it ?
The problem is, because it is a plugin, the change to header bar is done on a realized window. Gtk complains about this. This may be the cause of [`gtk_window_resize`](https://developer.gnome.org/gtk3/stable/GtkWindow.html#gtk-window-resize) failing to resize. It takes into account client side decorations size.

**Comment by nekohayo** [comment]
Indeed the window dimensions are correctly set on startup if the headerbar plugin is deactivated. Updating ticket title accordingly.

**Comment by lwindolf** [comment]
Finally found a solution by using g_idle_add () to postpone the code to not run in the same event that is running the gtk_widget_realize ()
