### ISSUE TITLE
Import OPML v2

### ISSUE THREAD

**Issue by duggalsu** [lwindolf/liferea#914]
Importing feed list with OPML v2 (exported from Flym android app) only displays folders with RSS feed icon. RSS feeds are not listed.

**Comment by lwindolf** [comment]
Could you provide an example OPML? That would help a lot.

**Comment by duggalsu** [comment]
Sorry for the delay. Try importing the following OPML - 

```
<?xml version="1.0" encoding="utf-8"?>
<opml version="2.0">
  <head>
    <dateCreated>Wed, 30 Dec 2020 17:29:51 GMT</dateCreated>
    <docs />
  </head>
  <body>
    <outline type="rss" title="tech">
      <outline type="rss" title="MIT Technology Review" xmlUrl="http://www.technologyreview.com/rss/rss.aspx" />
    </outline>
  </body>
</opml>
```

**Comment by Leiaz** [comment]
This fails because the first outline, which looks like it should be a folder, has type rss instead. If there is a type, Liferea will use it and not try to guess if it is wrong, so here it creates a feed with an empty url.
This looks like a bug in the exporting app to me.

@duggalsu You can fix your exported list by changing the type of your folders to "folder" instead of rss, or by just removing the type property.

**Comment by duggalsu** [comment]
@Leiaz thanks a lot!
