### ISSUE TITLE
http redirects

### ISSUE THREAD

**Issue by extua** [lwindolf/liferea#915]
I've got a consistent issue using liferea with a Hive WiFi hotspot in a cafe. When connecting to the hotspot, it redirects all http connections to the login page at https://connect.hivewifi.co.uk/connect

If I update my feeds before logging into the WiFi, all my non-https feed links are changed to https://connect.hivewifi.co.uk/connect

Is there a way to change this behaviour so that I don't lose the original feed links?

**Comment by lwindolf** [comment]
Not really. Because we want Liferea (and every other stateful web client) to properly follow permanent redirects. If a Wifi proxy incorrectly sends permanent redirects on an request it is broken.

We had user affected by this too in the past. I call it the hotel proxy hell.

If this happens to you and you immediately quit Liferea you can restore your feeds by running

     cp ~/config/liferea/feedlist.opml.backup ~/config/liferea/feedlist.opml

**Comment by extua** [comment]
Thanks for the backup restore fix, I'll make a note of that for next time I'm struck with this problem!
