### ISSUE TITLE
KISS feed sync (brainstorming)

### ISSUE THREAD

**Issue by nikoss** [lwindolf/liferea#94]
Hi, 
some thoughts here...

You were asking yourselves why the use of desktop feed readers is declining.
If the comments were open in Liferea's blog ;) , I would have commented, that,
probably, it is because, nowadays, people have many computers (desktop, tablet, phone, etc).
And they want to have access to their feeds from all of them.
So they prefer to use some online service.

I, too, so it happens, to have a second computer, now,
and I was searching for this synchronization thing.
I see that Liferea has support for Tiny Tiny RSS,
but this application is a kind of a "Pro".
It requires a lot for the average users 
(webserver hosting, database, cron, a few hours to set it up, and more).
And the commercial services...
why would I want to share my data with them?

So I thought that a simpler (Keep It Simple, Stupid) approach might be more useful,
even if it is more limited. 

The idea is for a free, open, sort of synchronization standard, 
that would require nothing but an editable text space online
(preferably protected by a password, for reading and writing).

That file could be a text file in an ftp server
(example: ftp://someserver.com/somename.txt)
or a wiki page
(eg http://somewiki.cc/Somepage?action=edit)
or a text file in some hosting service, 
or could be in a cloud service etc.
Or this file could be in your desktop computer, or LAN, 
to allow synchronization between different feed applications 
(like Liferea and Akregator).

So...
Liferea-A from Computer-A would export its state to this file.
Some basic information...
These are the categories (folders)
These are the feeds I subscribe to.
These are the articles (news) I have been informed of.
These I've read.
These I haven't read.
These ones are important.
File was last read on DATE by NAME
File was last edited on DATE by NAME
(DATE could be blank)
(NAME doesn't have to be unique, or could even be blank)

And, then, 
Liferea-B from Computer-B,
before updating it's feeds, would first read this text file,
and start from where it was left by Liferea-A.
And before closing, it would report its state to this file.

And then,
Akregator from Computer-C...
and so on...

There are some obvious issues that programmers would have to solve.
Like, what happens when multiple computers try to edit this file at the same time.
And I am in no position to suggest how the syntax of this file would be 
other than "as simple and as "lightweight" as possible".
Further more... 
is the free software community willing to cooperate on something like this?

But the main advantage is that it requires VERY LITTLE from the user.
Just write access, and a link, to a text file online (support for php editing, through plugins, would be nice)
A password.
A choice as to how often the program should report its state online 
(eg "whenever it changes", "every XXXX hours XX minutes XX seconds")
Always report state online before closing? YES/NO
Report time? YES/NO
Signature name to report: A DESCRIPTIVE NAME

This way, hopefully, desktop feed readers would be "back in the game".

And who knows, you might even be able to cover some of the development expenses.
Feed Readers developers could set up some relative service, for a very small, reasonable feed,
that some user might be willing to pay for.

Well, these are my thoughts on the subject...

**Comment by lwindolf** [comment]
@nodiscc Yes this could probably be implemented. Still for me it is not something I will do given the time I spend on the projec. Contribute :-) !!!

**Comment by qazip** [comment]
@lwindolf, I'll ask something that's not entirely off-topic but not entirely on-topic.

I tried syncing my liferea's settings (and by settings I mean everything, configs, feeds, read/unread, etc) and I just couldn't do it. I've a way of syncing files between my 2 computers (syncthing) but it just won't work. What are the files I need to sync in order to accomplish what I want? 

I tried the following:

```
ln -s ~/syncthing/liferea/config/* ~/.config/liferea/
ln -s ~/syncthing/liferea/share/* ~/.local/share/liferea/
```
And the files I've in each folder are:
`accels  cookies.txt  feedlist.opml  feedlist.opml.backup  liferea.css`

and:
`liferea.db`

However, whenever I open liferea, it seems like it doesn't read from my feedlist.opml, it just creates a new one. What am I doing wrong?

**Comment by lwindolf** [comment]
@qazip Synching those two directories is IMO correct. Symbolically linking the DB is problematic because when opened liferea.sqlite is set into a read-write locked state. When you copy it in this state it is not guaranteed to be usable.

Please run the startup on your sync target with --debug-all and post the log here.
