### ISSUE TITLE
RTL support not working anymore.

### ISSUE THREAD

**Issue by KevinScruff** [lwindolf/liferea#944]
From version 1.13.2, all the feed contents are showing from left to right, this makes some languages like Persian unreadable.

**Comment by lwindolf** [comment]
Please provide at least one feed URL for testing!

**Comment by KevinScruff** [comment]
https://kevinscruff.github.io/atom.xml

-------- Original Message --------

**Comment by KevinScruff** [comment]
> Please provide at least one feed URL for testing!

Sorry, i forgot.
https://kevinscruff.github.io/atom.xml

**Comment by lwindolf** [comment]
The feed currently renders for me like this

![image](https://user-images.githubusercontent.com/3315368/104132034-04b53780-537b-11eb-93a4-7a32834a031a.png)

I believe both the headline list and the item title are rendered correctly.
You are probably referring to the article content itself (being left-aligned)?

**Comment by KevinScruff** [comment]
Yeah, headlines are fine.
For the article, that can be fixed by adding a dir="auto" to paragraphs.

**Comment by KevinScruff** [comment]
When a left-to-right word/text is inside the paragraph, the paragraph becomes unreadable, which cannot fix that only by changing the alignment.

**Comment by KevinScruff** [comment]
A text with align="right": <p align="right">سلام hello تست</p>
Same text with dir="rtl": <p dir="rtl">سلام hello تست</p>

**Comment by lwindolf** [comment]
This is being caused by the new reader mode code: Webkit inspector shows the generated HTML looks like:

![Screenshot from 2021-01-10 21-29-27](https://user-images.githubusercontent.com/3315368/104134594-f0793680-538a-11eb-9950-46d9e2361a90.png)

So the text direction is properly detected and added as a &lt;p> below &lt;div id='content'>, but the content is then moved outside of the correct configured &lt;p> causing the RTL direction to be lost.

**Comment by lwindolf** [comment]
@KevinScruff Fixed. Please retest!

**Comment by KevinScruff** [comment]
Thanks
