### ISSUE TITLE
Combined view is gone

### ISSUE THREAD

**Issue by hast0011** [lwindolf/liferea#946]
The combined view is not available anymore on fedora 32. That was very comfortable and liferea is 90 % more unintuitive without.

**Comment by nekohayo** [comment]
Yes, that feature was deprecated with version 1.13.2, because it was too complex to maintain for the [limited manpower](https://www.openhub.net/p/liferea/contributors/summary) the project has. Quoting the release notes:

> 1.13 will drop the combined view aka 2-pane view mode. The feature was not maintained well, did not provide the same functionality as the 3-pane modes and did not scale well. Removing it will significantly simplify the code base and allows to implement "Reader mode" for the now single-item/single-document only views.

Personally, as a user, I agree with this change. I would prefer one or two views that work very well, than three views that are too buggy. If that means we can get fixes more easily for the widescreen view mode (for issue 534 for example) I'm all for it.

**Comment by hast0011** [comment]
OK, understand the manpower situation. 
I just was not prepared for that as I like to read feeds like a newspaper and wide view resembles that most. Totally agree with your opinion to have software with less features but more stable ones. However personally I would have dropped the other two views:-). Maybe the feature will come back after some time.
