### ISSUE TITLE
Need tooltips explaining the two states of the readability button

### ISSUE THREAD

**Issue by nekohayo** [lwindolf/liferea#947]
Since 1.13.4 there is now a readability toggle button in the header area of the feed items, however it is always unclear to me what state it is in, or what means what (in fact, I do not even understand, currently, if it is always turned on by default or not, because the option for it is presented as a "privacy" setting that controls whether the feature is _available_ at all, rather than whether it is "switched on" by default. Firefox's readability implementation is a bit clearer because when it's turned on, a) it looks very different b) the readability icon is blue instead of just changing opacity. A different color would be clearer.

But there is also the issue of discoverability. My parents could never figure out what this button does just by looking at the icon or clicking on it. It would need two tooltips to explain what it does and what state it is in; one for when it is turned on, and one for when it is turned off.

**Comment by lwindolf** [comment]
Good ideas

- [ ] let's switch to colored icon when enabled
- [ ] let's add a 2nd tooltip

**Comment by lwindolf** [comment]
Thinking some more on this I believe the solution needs to be different

- Wether reader mode is on/off is a property of the widget and should not be displayed in the widget itself (web browsers usually should it in the URL bar)
- Possible widget contexts in which to show the setting: context menu or address bar
- I believe while viewing headline it could be ok to have a check box in the context menu

I think above is the correct solution because it allows for the (planned) use case of extending the reader mode to all internal browsing. And to have reader mode on when doing external browsing per-default (or global per-preference). I think this will be one of the most important future features to have pretty much seamless feed/web reading in reader mode.

**Comment by lwindolf** [comment]
Reader mode toggle is now in the HTML view context menu.
- already works for headlines
- does not yet work for external content

**Comment by k4n30** [comment]
Came here to report an issue with the new reader mode toggle. Whilst I would have preferred the old way (the icon in the title bar), rather than having to right click and click the checkbox - but this isn't a show stopper.

By default I have reader mode ON, but for some feeds it breaks the content (not all links are shown) in the feeds item. Previously I could just click the icon next to the title and the view is changed from the default (i.e turns reader mode off if the default is on). However with the new check box toggle, the **_last selected option_** is the selected option in the right click context menu despite it being different to the default. The only way to fix this is to turn it off, and on again eg:

- Default - reader mode is on.
- Feed item 1 - reader mode is on (as it's the default), feed item doesn't display properly - so I turn it off (uncheck the box). The feed item is read and moved onto the next feed item.
- Feed item 2 - reader mode is on (as it's the default), but the checkbox shows it as off (due to feed item 1), feed item doesn't display properly, so I'd like to turn reader mode off. I right click the item and see it's already off (but it's actually not), I have to turn it on (click checkbox), but there's no change (as reader mode is now on). I then have to turn it off again (uncheck box) to have it properly display the feed.

I've tried to simplify the steps as much as possible, and understand it would be simpler to request the feed owner to investigate making reader mode work better, but it happens across multiple feed owners.

Let me know if I can provide any more information.

**Comment by lwindolf** [comment]
@k4n30 Just wanted to let you know that I'm working on a reasonable behaviour of this. Thanks for reporting in detail!

**Comment by lwindolf** [comment]
Button was removed and reworked into a context menu toggle.

**Comment by lwindolf** [comment]
Closing this as the issue of the ticket is IMO adressed.
